markdown: redcarpet
paygments: true
highlighter: pygments
safe: true
permalink: /:year/:month/:title/ 
exclude: ["README.md"]
auto: true

title: Coding Forever
author :
  name : diveinedu
  email : divein@yeah.net
  github : diveinedu
  twitter : diveinedu

production_url : http://diveinedu.github.io
