markdown: redcarpet
paygments: true
highlighter: pygments
safe: true
permalink: /:year/:month/:day/:title.html 
exclude: ["README.md"]
auto: true

sass:
    style: :compressed

title: Coding Forever
author :
  name : diveinedu
  email : divein@yeah.net
  github : diveinedu
  twitter : diveinedu

production_url : http://diveinedu.github.io

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  render_options:
